# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'memPOP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memPOP

  target 'memPOPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'memPOPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Charts', '~> 3.1.1'

end
